### ISSUE TITLE
一个疑惑

### ISSUE THREAD

**Issue by Enemy-77** [Ubpa/UCMake#2]
请问大佬，您的这个项目是用 CMake 的语法，封装 CMake 的功能吗？是为了自己更好的使用的同时顺带学习CMake吗？可以理解成是您的一个学习方法？因为好像看到您有多个这样类似的repo。可能这个issue并不和项目相关，还请见谅。

**Comment by Ubpa** [comment]
这个项目是为了自己更好地使用而存在的，我所有的其他工具库（如 UDRefl，Utopia 等）都是用 UCMake 构建项目、解决依赖问题等。
一般 U 开头的库不是学习用的，而就是一个工具库，作为一个开源项目。
